# Generated by Django 3.1.4 on 2020-12-24 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shellcode', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shellcode',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('hash_md5', models.CharField(max_length=200)),
                ('shellcode', models.TextField()),
                ('pub_date', models.DateTimeField(auto_now=True)),
                ('number', models.IntegerField()),
                ('packaging', models.CharField(max_length=200)),
                ('path', models.FileField(max_length=200, upload_to='')),
            ],
            options={
                'ordering': ('-pub_date',),
            },
        ),
    ]
