# Generated by Django 3.1.4 on 2020-12-25 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shellcode', '0002_shellcode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shellcode',
            old_name='path',
            new_name='filename',
        ),
    ]
